### ISSUE TITLE
error: 'Leanplum/Leanplum-Swift.h' file not found

### ISSUE THREAD

**Issue by sidferreira** [Leanplum/Leanplum-ReactNative-SDK#66]
Error:

```
ios/Pods/Leanplum-iOS-SDK/LeanplumSDK/LeanplumSDK/Classes/Utilities/Vendor/SocketIO/Leanplum_SocketIO.m:47:9: fatal error: 'Leanplum/Leanplum-Swift.h' file not found
#import <Leanplum/Leanplum-Swift.h>
```

> @leanplum/react-native-sdk@^1.2.1 (but resolved 1.3.0)
> - Leanplum-iOS-SDK (4.1.0)

**Comment by RP-alissonpaschoal** [comment]
same problem here using RN 0.67.4, could you fix it?

**Comment by AugustoAleGon** [comment]
I have the same issue.

**Comment by nzagorchev** [comment]
This is an issue with cocoapods when using static linking, for pods that use mixed languages. You can link Leanplum dynamically, by adding the following code in Podfile:
```
dynamic_frameworks = ['Leanplum-iOS-SDK']
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
    installer.pod_targets.each do |pod|
        if dynamic_frameworks.include?(pod.name)
          puts "Setting dynamic linking for #{pod.name}"
          def pod.build_type;
            Pod::BuildType.dynamic_framework
          end
        end
      end
  end
```

**Comment by nzagorchev** [comment]
@AugustoAleGon Is this working for you?

**Comment by Bej-Technologies** [comment]
@nzagorchev I got the same issue after upgrading and I can confirm the fix you commented worked for me

**Comment by AugustoAleGon** [comment]
@nzagorchev yes. this works for me.

**Comment by crherman7** [comment]
@nzagorchev can you update the documentation based on this solution? In react native most projects cannot use `use_frameworks!` as it's not fully supported yet. Therefore we need to specify individual pods as a specific build type i.e. `Leanplum-iOS-SDK` via the `pre_install` hook seen above or through a potential cocoapods plugin that unfortunately is maintained for newer versions of cocoapods. Now that 2.0.0 has been released, it now requires `CleverTap-iOS-SDK` pod. This will bring up subsequent compile time errors. This is due to build types cascade to their dependencies. `CleverTap-iOS-SDK` also depends on `SDWebImage`. So both of these additional pods will need to be added to the array seen in the above solution.
